# Generated by Django 4.2.5 on 2023-09-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='accounts',
        ),
    ]
