# Generated by Django 4.2.5 on 2023-09-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0002_rename_users_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='accounts',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
