# Generated by Django 4.2.5 on 2023-09-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
