# Generated by Django 4.2.5 on 2023-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('News', 'News'), ('Tutorial', 'Tutorial'), ('Business', 'Business')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='statue',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], max_length=2),
        ),
    ]
