# Generated by Django 4.2.5 on 2023-10-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.CharField(
                choices=[
                    ("News", "News"),
                    ("Tutorial", "Tutorial"),
                    ("Business", "Business"),
                ],
                default="Business",
                max_length=10,
            ),
        ),
    ]
